### ISSUE TITLE
Error on login/new installation

### ISSUE THREAD

**Issue by nkellmeyer** [whahn1983/pycashflow#11]
I just installed this in a docker container on my synology NAS.  I created a login, and upon signing in, got a 500 server error to screen.

Error stack is as follows:

ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/main.py", line 35, in index
    return render_template('index.html', title='Index', todaydate=todaydate, balance=balance.amount,
                                                                                     ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'amount'

**Comment by whahn1983** [comment]
Fixed in 1.9.11.  Tested on a fresh docker container.

**Comment by nkellmeyer** [comment]
Thanks for the quick response!  Agreed, I can log in now.  I've tried
setting a starting balance.  I can see the values I've tried have been set
in the db.sqlite database, but I'm not seeing it reflected on screen.  I
also don't see an obvious way to add transactions, i.e. there are no
buttons on the transaction page.  There are buttons on the schedules page,
but only the download button works, giving me a mostly empty csv file.

I was just inspecting the pages with web developer tools to see if there
were any events firing on the schedule page when hitting buttons, and I
spotted the rendered template, when including font awesome, the first 3
quotes are actually MS Office doublequote characters -- only the last one
is a regular quote, so my browser isn't loading in the style sheet.
<link rel=”stylesheet” href=”
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
">

This is present on this line in each of the following:
base.html
profile_guest.html
index_guest.html

**Comment by nkellmeyer** [comment]
Actually, I just realized that style sheet is included twice on each of
those pages -- once with regular quotes, and once with the wonky ones, so
that explains why I can see fa icons.  The upload button makes it seem like
it wants to give me a modal, but nothing shows up for me in chrome or FF.
Were you targeting Edge or iOS browsers with this app?

**Comment by whahn1983** [comment]
You may have pulled in between commits.  I found a second issue with the schedule modals which I fixed as well which should activate the modal to add a schedule even when the table is empty.  For the transactions table, that is a generated table from the schedule table of the next 60 days of transactions based on the scheduled.  Try to pull latest again and see if you can add some schedules.  Then the transaction table will populate.
